name: mi_card_flutter_1
description: "Create A Small Business Card App With Flutter"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/

  fonts:
    - family: PlayWrite_IS
      fonts:
        - asset: lib/fonts/PlayWrite_IS.ttf

    - family: SourceCodePro
      fonts:
        - asset: lib/fonts/SourceCodePro.ttf
